CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 12333 main.py  \
--savepath suprobcon_temp_0.5_supcon_detach \
--in_d 512 \
--out_d 128 \
--train_bs 1024 \
--scheduler cosineanneal \
--training_epoch 100 \
--warm_epoch 5 \
--init_lr 0.1 \
--scale_factor 8 \
--temperature 0.5 \
--save_last_best 1